
version: 2.1

jobs:

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print Hello"
          command: echo Hello World > output
           

workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output