
version: 2.1

jobs:

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print Hello"
          command: echo Hello World > output
      - persist_to_workspace:
        root: /home/circleci/project
        paths:
        - output
  pwd: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "print directory"
          command: pwd

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workplace:
        at: /home/circleci/project
      - run:
          name: "print output"
          command: cat output       

workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output
      - pwd
      - print_output_file
          requires: [save_hello_world_output]