
version: 2.1

defaults: &container
  docker:
      - image: circleci/node:13.8.0

jobs:

  save_hello_world_output:
    <<: *container
    steps:
      - run: |
          echo Hello World > output
          pwd
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - output

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run: cat output       

workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires: [save_hello_world_output]