
version: 2.1

jobs:

  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Hello World > output
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - output
  pwd: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: pwd

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /home/circleci/project
      - run: cat output       

workflows:
  save-hello-workflow:
    jobs:
      - save_hello_world_output
      - pwd
      - print_output_file:
          requires: [save_hello_world_output]